### ISSUE TITLE
Investigating the theoretical solutions

### ISSUE THREAD

**Issue by m4n1c22** [m4n1c22/os_labs#16]
Kindly check into the various **theoretical** possibilities dealt with the given [lab exercise](https://github.com/m4n1c22/os_labs/blob/master/os_lab_3/lab3-lkm-producer-consumer.pdf). 
- Open a Readme under the name **_'theoretical solutions.md' _**
- Provide valid insights into the **_solutions_** of the questions dealt in the **_exercise_**.
- And also for the possible in external questions with it's solution which, can _hypothesized_ from the given **_exercise_**.

**Comment by m4n1c22** [comment]
Kindly initiate the task by starting off a document with same.

**Comment by pascals-ager** [comment]
All done.
